export const SELECTED_IMAGE = 'SELECTED_IMAGE';
export const FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS';
export const SELECTED_VIDEO = 'SELECTED_VIDEO';
export const SHUTTER_VIDEOS_SUCCESS = 'SHUTTER_VIDEOS_SUCCESS';
export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';

//PRODUCT ACTIONS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_COMPONENT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_COMPONENT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_COMPONENT_FAILURE = 'ADD_PRODUCT_FAILURE';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';
export const GET_LIST_OF_PRODUCTS = 'GET_LIST_OF_PRODUCTS';
export const GET_LIST_OF_PRODUCTS_SUCCESS = 'GET_LIST_OF_PRODUCTS_SUCCESS';
export const GET_LIST_OF_PRODUCTS_FAILURE = 'GET_LIST_OF_PRODUCTS_FAILURE';
export const GET_PRODUCT = 'GET_PRODUCT';
export const SELECTED_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';




